_extends: .github
tag-template: $NEXT_MINOR_VERSION
name-template: $NEXT_MINOR_VERSION
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
template: |
  ## What's Changed

  $CHANGES
